# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ad601e45d8744aa14f9278bd2ee931c85e1a64904b9fd8a46bea906f08739030de3b639992cbfd34ed898435f0ff2fd3b292d3c096724b13ba907c4421df21

test:
  secret_key_base: 94edb2dac207497c3483b7e77e768ee292e11c45f00f2ecc7fc25fa8a0578a88b5a098f0dffe462438439c865582c502f5a34484a510ae0125ef6b60012d1499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
